version: "3"
services:

  api:
    container_name: grow_interview
    # restart: always
    tty: true
    build: 
      context: ./
      dockerfile: .docker/node/Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - "./api:/var/www/html"
    ports:
    - "3000:3000"
    - "9229:9229" #debug port 
    